apiVersion: v2
name: ingress-nginx
description: ingress-nginx-chart
version: 0
dependencies:
  - name: "ingress-nginx"
    version: "4.8.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress-nginx
