apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kranurag78/gitopss.git
    path: cert-manager
    directory:
      recurse: true
    targetRevision: main
    helm:
      valueFiles:
        - values-cert-manager.yaml
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: cert-manager
    name: kind
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
